# Run with docker run -d -p 5000:5000 <image_name>
FROM python:3.9 AS build-env

COPY . /app
WORKDIR /app

RUN pip install --target=./ --no-cache-dir -r requirements.txt
#----
FROM gcr.io/distroless/python3-debian11:debug-arm64

COPY --from=build-env /app /app
WORKDIR /app

EXPOSE 5000

CMD ["app.py"]